import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.GroupAction.Transitive
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.Data.ZMod.QuotientGroup

namespace BurnsidePrimeDegreeTheorem

open MulAction

/-- A transitive permutation group of prime degree contains an element whose order is the degree. -/
lemma exists_element_of_prime_order
    {α : Type*} [Fintype α]
    {G : Subgroup (Equiv.Perm α)} [IsPretransitive G α]
    (hp : (Fintype.card α).Prime) :
    ∃ τ : G, orderOf τ = Fintype.card α := by
  classical
  haveI : Fact (Fintype.card α).Prime := ⟨hp⟩
  let a : α := Classical.choice (Fintype.card_pos_iff.mp hp.pos)
  have hdvd : Fintype.card α ∣ Nat.card G := by
    have h := Subgroup.index_mul_card (MulAction.stabilizer G a)
    rw [MulAction.index_stabilizer_of_transitive, Nat.card_eq_fintype_card] at h
    exact ⟨Nat.card (MulAction.stabilizer G a), h.symm⟩
  exact exists_prime_orderOf_dvd_card' (Fintype.card α) hdvd

/-- An element of order equal to the prime degree is a cycle on the whole underlying type. -/
lemma prime_order_element_isCycle
    {α : Type*} [Fintype α]
    {G : Subgroup (Equiv.Perm α)}
    (τ : G) (hp : (Fintype.card α).Prime)
    (hord : orderOf τ = Fintype.card α) :
    (τ : Equiv.Perm α).IsCycle := by
  apply Equiv.Perm.isCycle_of_prime_order'' hp
  exact (Subgroup.orderOf_mk (τ : Equiv.Perm α) τ.2).symm.trans hord

/-- The cyclic subgroup generated by an element of prime full order acts transitively. -/
lemma cyclicSubgroup_isPretransitive
    {α : Type*} [Fintype α]
    {G : Subgroup (Equiv.Perm α)}
    (τ : G) (hp : (Fintype.card α).Prime)
    (hord : orderOf τ = Fintype.card α) :
    IsPretransitive (Subgroup.zpowers τ) α := by
  classical
  have hcycle := prime_order_element_isCycle τ hp hord
  have horder : orderOf (τ : Equiv.Perm α) = Fintype.card α :=
    (Subgroup.orderOf_mk (τ : Equiv.Perm α) τ.2).symm.trans hord
  have hsupp : (τ : Equiv.Perm α).support = Finset.univ := by
    apply Finset.eq_univ_of_card
    rw [← hcycle.orderOf, horder]
  constructor
  intro a b
  have ha : (τ : Equiv.Perm α) a ≠ a := by
    rw [← Equiv.Perm.mem_support, hsupp]
    exact Finset.mem_univ a
  have hb : (τ : Equiv.Perm α) b ≠ b := by
    rw [← Equiv.Perm.mem_support, hsupp]
    exact Finset.mem_univ b
  obtain ⟨k, hk⟩ := hcycle.exists_zpow_eq ha hb
  exact ⟨⟨τ ^ k, k, rfl⟩, hk⟩

/-- The cyclic subgroup generated by an element of prime full order has trivial stabilizers. -/
lemma cyclicSubgroup_stabilizer_eq_bot
    {α : Type*} [Fintype α]
    {G : Subgroup (Equiv.Perm α)}
    (τ : G) (hp : (Fintype.card α).Prime)
    (hord : orderOf τ = Fintype.card α) (a : α) :
    MulAction.stabilizer (Subgroup.zpowers τ) a = ⊥ := by
  letI : IsPretransitive (Subgroup.zpowers τ) α :=
    cyclicSubgroup_isPretransitive τ hp hord
  rw [Subgroup.eq_bot_iff_card]
  have hindex := Subgroup.index_mul_card (MulAction.stabilizer (Subgroup.zpowers τ) a)
  have hzcard : Nat.card (Subgroup.zpowers τ) = Fintype.card α := by
    rw [Nat.card_zpowers, hord]
  rw [MulAction.index_stabilizer_of_transitive, hzcard, Nat.card_eq_fintype_card] at hindex
  have hindex' :
      Fintype.card α * Nat.card (MulAction.stabilizer (Subgroup.zpowers τ) a) =
        Fintype.card α * 1 := by
    simpa using hindex
  exact Nat.eq_of_mul_eq_mul_left hp.pos hindex'

end BurnsidePrimeDegreeTheorem
